# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: run-unittests
        name: Run Unit Tests
        entry: bash -c 'cd simple_calculator/ && python -m unittest test_calculator.py'
        language: system
        pass_filenames: false
        always_run: true
